project:
  type: website
  output-dir: docs

website:
  title: "ilovedata"
  navbar:
    left:
     - href: index.qmd
       text: Home
     - href: lectures.qmd
       text: Lectures

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



